
# www.ros.org/wiki/octomap_server

frame_id:       Pioneer3AT/map
resolution:     0.05
base_frame_id:  Pioneer3AT/base_link

height_map:     true
color/r:        0.0
color/g:        0.7
color/b:        0.0
color/a:        1.0

sensor_model/max_range: 30.0
sensor_model/hit:       0.7
sensor_model/miss:      0.4
sensor_model/min:       0.12
sensor_model/min:       0.97

latch:                  false

filter_ground:                  false
ground_filter/distance:         0
ground_filter/angle:            0
ground_filter/plane_distance:   0

pointcloud_min_z: -1000
pointcloud_max_z:  1000

occupancy_min: 0.02
occupancy_max: 0.75



