#
# RosAria Driver Node
#

port:               /dev/ttyUSB0
debug_aria:         false
aria_log_filename:  Aria.log

tf_prefix:          Pioneer3AT

TicksMM:            141
DriftFactor:        91
RevCount:           32675

cmd_vel_timeout:    2.0
